### ISSUE TITLE
Remove Lo-Dash dependency

### ISSUE THREAD

**Issue by robatron** [emflores/carousel-lite#5]
Remove the dependency on [`lodash-compat/array/findIndex` in `lib.js`](https://github.com/emflores/carousel-lite/blob/e8ee926cc33b79e8732467a8b78f377b0abbbd3c/lib.js#L3). This should reduce the total package size from 59 K --> 7.5 K (-51.5 K).

**Comment by emflores** [comment]
Completely agree. This, I suppose, is the downside of lodash. When something like `findIndex` requires 1/2 the lodash library (joking/not joking) to function, it almost makes it unusable in modules like this.

**Comment by robatron** [comment]
Totally. Luckily, `carousel-light` is only dependent on `findIndex` which is simple to implement with an old-school `for` loop.
